FROM postgres:16

# We need to be explicit about this one
VOLUME /var/lib/postgresql/data

# Added to alleviate the current shortcoming of Golem storage implementation which requires a volume
# to be defined in order to access the storage on the provider
VOLUME /storage