FROM postgres:16

# We need to be explicit about this one
VOLUME /var/lib/postgresql/data/pgdata

# If you plan to `transfer` files into the activity, make sure you're having a proper volume for this
VOLUME /golem/work