FROM node:18-alpine

RUN apk upgrade --update-cache --available && apk add openssl
RUN rm -rf /var/cache/apk/*

# Added to alleviate the current shortcoming of Golem storage implementation which requires a volume
# to be defined in order to access the storage on the provider
VOLUME /storage
