# reference: https://github.com/docker-library/docker/blob/75c73110b6ee739dab28c30b757eec51484968c1/27/dind/Dockerfile
FROM docker:27-cli

# Important for golem to be able to write files to disk
VOLUME /var/lib/docker /var/run/docker