# reference: https://github.com/docker-library/docker/blob/75c73110b6ee739dab28c30b757eec51484968c1/27/dind/Dockerfile
FROM docker:27

# Added to alleviate the current shortcoming of Golem storage implementation which requires a volume
# to be defined in order to access the storage on the provider
VOLUME /storage