name: Build Node.js image
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build-gvmi:
    name: Build Node.js GVMI

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: [18, 18-alpine, 20, 20-alpine, latest]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Install gvmkit-build
        run: pip install gvmkit-build

      - name: Build ${{ matrix.version }}
        working-directory: ./images/node
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: |
          docker build -t golem/node:${{ matrix.version }} -f Dockerfile.${{ matrix.version }} .
          gvmkit-build --push golem/node:${{ matrix.version }}