name: Build Docker image
on:
  workflow_dispatch:
  schedule:
    # Do it on Mondays :)
    - cron: "0 0 * * 1"
jobs:
  build-gvmi:
    name: Build Docker GVMI

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: [27]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Install gvmkit-build
        run: pip install gvmkit-build

      - name: Build ${{ matrix.version }}
        working-directory: ./images/node
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: |
          docker build -t golem/docker:${{ matrix.version }} -f Dockerfile.${{ matrix.version }} .
          gvmkit-build --push golem/docker:${{ matrix.version }}