name: Build Node.js image
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build-gvmi:
    name: Build Node.js GVMI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Install gvmkit-build
        run: pip install gvmkit-build

      - name: Build the image and push to registry
        working-directory: ./images/node
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: ./build.sh